import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer"
import Providers from './providers'
import { Suspense } from "react";

const albertSans = {
  variable: "--font-albert-sans",
  style: "normal",
  weight: "400",
  src: "https://fonts.googleapis.com/css2?family=Albert+Sans:wght@400;500;600;700&display=swap",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayoutFortitude({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href={albertSans.src} rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-albert-sans antialiased`}
        style={{ fontFamily: "'Albert Sans', sans-serif" }}
      >
        <Providers>
          <main>
            <Suspense fallback={<div className="h-20 bg-white"></div>}>
              <Header />
            </Suspense>
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}